# This workflow will run tests using node.

name: test-runner

on:
  #push:
    #branches:
      #- main
  #pull_request:
    #branches:
      #- main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        #run: |
          #echo "TOKEN: $token"
          #echo "USER: $user"
          #npm test
        run: npm script-t
        env:
          token: ${{ secrets.TOKEN }}
          user: ${{ secrets.USER }}
